### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by JimenaEB** [AlmuUve/HuMind-final-project#8]
Tenemos cositas que cambiar en los modelos, allá van:
1. Todos los Strings que no sepamos a que limitarlos los podemos cambiar por VARCHAR
2. La password debe ser privada _password y de tipo password
3. is_active lo podemos iniciar a True poniendo default=True
4. is_psychologist debería no admitir nulos, o lo eres o no lo eres
5. user_company también tiene que tener el delete cascade
6. No necesitáis en User el to_dict por lo que hemos hablado
7. El método  update_single_user(user_data, id): tal como lo habéis definido es un @staticmethod
8. No hacemos borrados de verdad, sólo soft-deletes cambiando is_active a False
9. No entiendo muy bien porqué category tiene un is_active
10. max_people debería o no aceptar nulos o poner por defecto un valor

https://github.com/AlmuUve/HuMind-final-project/blob/9bb37e14d88f92a35a46582ab03650111334f290/src/api/models.py#L1

**Comment by AlmuUve** [comment]
En la 9 habíamos puesto el is_active para cuando se seleccione una categoría, pasarla a True y saber cuál está seleccionada, pero igual no es la solución más óptima... nos dices! 

Ya solo nos queda arreglar la 7 y 8 que en realidad no deberían ir en esta rama, ¿te lo subimos aquí y la 7 y 8 cada una en su rama?

**Comment by JimenaEB** [comment]
Prefiero cada una en su rama, por fa!
No entiendo muy bien lo de pasar una categoría a True

**Comment by AlmuUve** [comment]
arreglado todo :)
